package spinner

// loading style
var (
	// LoadingA ...
	LoadingA = []string{"⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"}
	// LoadingB ...
	LoadingB = []string{"\\", "|", "/", "-"}
	// LoadingC ...
	LoadingC = []string{"🌕", "🌖", "🌗", "🌘", "🌑", "🌒", "🌓", "🌔"}
	// LoadingD ...
	LoadingD = []string{"🕐", "🕑", "🕒", "🕓", "🕔", "🕕", "🕖", "🕗", "🕘", "🕙", "🕚", "🕛"}
	// LoadingE ...
	LoadingE = []string{"▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"}
)

// status symbol
var (
	// SymbolA ...
	SymbolA = []string{"✔︎", "✘"}
	// SymbolB ...
	SymbolB = []string{"✓", "✗"}
	// SymbolC ...
	SymbolC = []string{"✅", "❎"}
	// SymbolD ...
	SymbolD = []string{"👍", "👎"}
	// SymbolE ...
	SymbolE = []string{"💚", "💔"}
)
